services:
  database:
    restart: unless-stopped
    image: postgres:latest
    container_name: database
    volumes:
      - ~/.pg/shampsdev-db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"