services:
  database:
    restart: unless-stopped
    image: postgres:latest
    container_name: database
    volumes:
      - ~/.pg/shampsdev-db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - shampsdev-db
  backend:
    container_name: backend
    build: .
    env_file:
      - .env
    environment:
      HTTP_PORT: 8000
      POSTGRES_HOST: database
    depends_on:
      - database
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - shampsdev-db

networks:
  shampsdev-db:
    name: shampsdev-db
    external: true